CREATE DATABASE IF NOT EXISTS prakse
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_latvian_ci;
USE prakse;
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);